name: Pool Scraper

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Zurich
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set cache date
      run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
    
    # Define a fixed path for the Conda environment
    - name: Set Conda env path
      run: echo "CONDA_ENV_PATH=/home/runner/conda-cache-env" >> $GITHUB_ENV
    
    # Try to restore the cached environment 
    - name: Cache Conda environment
      uses: actions/cache@v3
      with:
        path: ${{ env.CONDA_ENV_PATH }}
        key: conda-${{ runner.os }}-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
      id: conda-cache
    
    # Set up Conda only if no cache hit
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.10'
        activate-environment: pool-scraper
        environment-file: environment.yml
        use-only-tar-bz2: true
        environment-path: ${{ env.CONDA_ENV_PATH }}
      if: steps.conda-cache.outputs.cache-hit != 'true'
        
    - name: Run scraper
      shell: bash -l {0}  # Needed for conda activation
      run: |
        # If cache hit, we need to "register" the environment with conda
        if [[ "${{ steps.conda-cache.outputs.cache-hit }}" == 'true' ]]; then
          source $CONDA/etc/profile.d/conda.sh
          conda activate ${{ env.CONDA_ENV_PATH }}
        else
          conda activate pool-scraper
        fi
        python pool_scraper.py --once
      
    - name: Commit and push if data changed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add data/*.csv data/*.png
        # Only commit if there are changes
        git diff --staged --quiet || (git commit -m "Update pool guest data $(date '+%Y-%m-%d %H:%M:%S')" && git push)